export const LANGUAGES = {
    en: {
        welcomeMessage: 'Welcome to the Pokemon Info Downloader CLI!',
        enterPokemonName: 'What pokemon do you want to research?',
        infoPrompt: 'What info do you want to download?',
        askForAnotherPokemon: 'Do you want to research another pokemon?',
        downloadSuccess: 'Successfully downloaded information for',
        errorFetchingInfo: 'Error fetching Pokemon information:',
        'INVALID_POKEMON': 'Invalid Pokemon',
        'abilities': 'Abilities',
        'evolution-chain': 'Evolution Chain',
        'stats': 'Stats',
        'official-artwork': 'Official Artwork',
    },
    ro: {
        welcomeMessage: 'Bine ați venit la Pokemon Info Downloader CLI!',
        enterPokemonName: 'Introduceți numele Pokemon-ului:',
        infoPrompt: 'Ce informații doriți să descărcați?',
        askForAnotherPokemon: 'Doriți să cautati un alt Pokemon?',
        downloadSuccess: 'Informații descărcate cu succes pentru',
        errorFetchingInfo: 'Eroare la preluarea informațiilor despre Pokemon:',
        'INVALID_POKEMON': 'Pokemon invalid',
        'abilities': 'Abilitati',
        'evolution-chain': 'Ordinea evoluției',
        'stats': 'Caracteristici',
        'official-artwork': 'Designul oficial',
    },
    es: {
        welcomeMessage: 'Bienvenido al Pokemon Info Downloader CLI!',
        enterPokemonName: '¿Qué Pokémon quieres investigar?',
        infoPrompt: '¿Qué información quieres descargar?',
        askForAnotherPokemon: '¿Quieres investigar otro pokemon?',
        downloadSuccess: 'Información descargada con éxito para',
        errorFetchingInfo: 'Error al obtener información de Pokemon:',
        'INVALID_POKEMON': 'Invalid Pokemon in spaniola',
        'abilities': 'habilidades',
        'evolution-chain': 'Cadena de evolución',
        'stats': 'Estadísticas',
        'official-artwork': 'obra de arte oficial',
    },
};
