export const LANGUAGES = {
    en: {
        'PROMPT_ASK_TOPIC': "What would you like search?",
        'PROMPT_WELCOME_MESSAGE': 'Welcome to the Pokemon Info Downloader CLI!',
        'PROMPT_ASK_POKEMON': 'What pokemon do you want to research?',
        'PROMPT_ASK_DOWNLOAD': 'What info do you want to download?',
        'PROMPT_ASK_ANOTHER_POKEMON': 'Do you want to research another pokemon?',
        downloadSuccess: 'Successfully downloaded information for',
        errorFetchingInfo: 'Error fetching Pokemon information:',
        'PROMPT_ASK_DIGIMON': 'What digimon do you want to research?',
        'ERRORS_FETCH_POKEMON': 'Failed to fetch pokemon',
        'ERRORS_FETCH_DIGIMON': 'Failed to fetch digimon',
        'INVALID_EVOLUTION_CHAIN': 'Invalid evolution chain',
        'abilities': 'Abilities',
        'evolution-chain': 'Evolution Chain',
        'stats': 'Stats',
        'official-artwork': 'Official Artwork',
    },
    ro: {
        'PROMPT_ASK_TOPIC': "Ce doriți să căutați?",
        "PROMT_ASK_POKEMON": "",
        "ERRORS_INVALID_POKEMON": "",
        'PROMPT_WELCOME_MESSAGE': 'Bine ați venit la Pokemon Info Downloader CLI!',
        'PROMPT_ASK_POKEMON': 'Introduceți numele Pokemon-ului:',
        'PROMPT_ASK_DOWNLOAD': 'Ce informații doriți să descărcați?',
        'PROMPT_ASK_ANOTHER_POKEMON': 'Doriți să cautati un alt Pokemon?',
        'PROMPT_ASK_DIGIMON': 'What digimon do you want to research? ro',
        downloadSuccess: 'Informații descărcate cu succes pentru',
        errorFetchingInfo: 'Eroare la preluarea informațiilor despre Pokemon:',
        'ERRORS_FETCH_POKEMON': 'Ai introdus un nume de Pokemon invalid, incercati din nou.',
        'ERRORS_FETCH_DIGIMON': 'Ai introdus un nume de Digimon invalid, incercati din nou.',
        'INVALID_EVOLUTION_CHAIN': 'Invalid evolution chain',
        'abilities': 'Abilitati',
        'evolution-chain': 'Ordinea evoluției',
        'stats': 'Caracteristici',
        'official-artwork': 'Designul oficial',
    },
    es: {
        'PROMPT_ASK_TOPIC': "¿Qué te gustaría buscar?",
        'PROMPT_WELCOME_MESSAGE': 'Bienvenido al Pokemon Info Downloader CLI!',
        'PROMPT_ASK_POKEMON': '¿Qué Pokémon quieres investigar?',
        'PROMPT_ASK_DOWNLOAD': '¿Qué información quieres descargar?',
        'PROMPT_ASK_ANOTHER_POKEMON': '¿Quieres investigar otro pokemon?',
        'PROMPT_ASK_DIGIMON': 'What digimon do you want to research? es',
        downloadSuccess: 'Información descargada con éxito para',
        errorFetchingInfo: 'Error al obtener información de Pokemon:',
        'ERRORS_FETCH_POKEMON': 'Ingresaste un nombre de Pokémon no válido, inténtalo de nuevo.',
        'ERRORS_FETCH_DIGIMON': 'Ingresaste un nombre de Digimon no válido, inténtalo de nuevo.',
        'INVALID_EVOLUTION_CHAIN': 'Invalid evolution chain',
        'abilities': 'habilidades',
        'evolution-chain': 'Cadena de evolución',
        'stats': 'Estadísticas',
        'official-artwork': 'obra de arte oficial',
    },
};
