export const LANGUAGES = {
    en: {
        'PROMPT_ASK_TOPIC': "What would you like search?",
        'PROMPT_WELCOME_MESSAGE': 'Welcome to the Pokemon Info Downloader CLI!',
        'PROMPT_ASK_POKEMON': 'What pokemon do you want to research?',
        'PROMPT_ASK_DOWNLOAD': 'What info do you want to download?',
        'PROMPT_ASK_ANOTHER_POKEMON': 'Do you want to research another pokemon?',
        'PROMPT_ASK_DIGIMON': 'What digimon do you want to research?',

        'ERRORS_FETCH_POKEMON': 'Failed to fetch pokemon',
        'ERRORS_FETCH_DIGIMON': 'Failed to fetch digimon',
        'ERRORS_INVALID_TOPIC': 'Invalid topic',
        'ERRORS_INVALID_POKEMON': 'Invalid pokemon name',
        'ERRORS_INVALID_POKEMON_INFO': 'Invalid pokemon info',
        'ERRORS_INVALID_LANGUAGE': 'Invalid language',

        'abilities': 'Abilities',
        'evolution-chain': 'Evolution Chain',
        'stats': 'Stats',
        'official-artwork': 'Official Artwork',
    },
    ro: {
        'PROMPT_ASK_TOPIC': "Ce doriți să căutați?",
        'PROMPT_WELCOME_MESSAGE': 'Bine ați venit la Pokemon Info Downloader CLI!',
        'PROMPT_ASK_POKEMON': 'Introduceți numele Pokemon-ului:',
        'PROMPT_ASK_DOWNLOAD': 'Ce informații doriți să descărcați?',
        'PROMPT_ASK_ANOTHER_POKEMON': 'Doriți să cautati un alt Pokemon?',
        'PROMPT_ASK_DIGIMON': 'What digimon do you want to research? ro',

        'ERRORS_FETCH_POKEMON': 'Ai introdus un nume de Pokemon invalid, incercati din nou.',
        'ERRORS_FETCH_DIGIMON': 'Ai introdus un nume de Digimon invalid, incercati din nou.',
        'ERRORS_INVALID_TOPIC': 'Categorie invalida',
        'ERRORS_INVALID_POKEMON': 'Nume de Pokemon invalid',
        'ERRORS_INVALID_POKEMON_INFO': 'informatii de Pokemon invalide',
        'ERRORS_INVALID_LANGUAGE': 'Limba invalida',

        'abilities': 'Abilitati',
        'evolution-chain': 'Ordinea evoluției',
        'stats': 'Caracteristici',
        'official-artwork': 'Designul oficial',
    },
    es: {
        'PROMPT_ASK_TOPIC': "¿Qué te gustaría buscar?",
        'PROMPT_WELCOME_MESSAGE': 'Bienvenido al Pokemon Info Downloader CLI!',
        'PROMPT_ASK_POKEMON': '¿Qué Pokémon quieres investigar?',
        'PROMPT_ASK_DOWNLOAD': '¿Qué información quieres descargar?',
        'PROMPT_ASK_ANOTHER_POKEMON': '¿Quieres investigar otro pokemon?',
        'PROMPT_ASK_DIGIMON': 'What digimon do you want to research? es',

        'ERRORS_FETCH_POKEMON': 'Ingresaste un nombre de Pokémon no válido, inténtalo de nuevo.',
        'ERRORS_FETCH_DIGIMON': 'Ingresaste un nombre de Digimon no válido, inténtalo de nuevo.',
        'ERRORS_INVALID_TOPIC': 'Categoría inválida',
        'ERRORS_INVALID_POKEMON': 'Pokemon no válido',
        'ERRORS_INVALID_POKEMON_INFO': 'información de Pokemon no válida',
        'ERRORS_INVALID_LANGUAGE': 'Idioma no válido',

        'abilities': 'habilidades',
        'evolution-chain': 'Cadena de evolución',
        'stats': 'Estadísticas',
        'official-artwork': 'obra de arte oficial',
    },
};
